services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s   

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
